services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    ports: 
      - ${HOST_MACHINE_DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${PATH_OF_BIND_MOUNT}/db:/var/lib/postgresql/data
    networks:
      - market_data_aggregator_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build: .
    command: >
      alembic upgrade head
    env_file: .env
    networks:
      - market_data_aggregator_network
    depends_on:
      db:
        condition: service_healthy

  app:
    build: .
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    env_file: .env
    volumes:
      - ${PATH_OF_BIND_MOUNT}/app_logs:/app/logs
    networks:
      - market_data_aggregator_network
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

networks:
  market_data_aggregator_network:
