"""
Initial migration

Revision ID: f64edb5bb1e3
Revises: 
Create Date: 2026-05-23 20:39:59.240072
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f64edb5bb1e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithm_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('algorithm', sa.Enum('ADX_CONSOLIDATION_STAGE_TRANSITION', 'ADX_EXTREME_TREND_REACHED', 'ADX_POS_DI_GROWTH', 'ADX_POS_DI_DECLINE', 'ADX_NEG_DI_GROWTH', 'ADX_NEG_DI_DECLINE', 'ADX_DI_BULLISH_CROSSOVER', 'ADX_DI_BEARISH_CROSSOVER', 'ENVELOPE_LOWER_BOUNDARY_BREAKOUT', 'ENVELOPE_UPPER_BOUNDARY_BREAKOUT', 'MACD_SIGNAL_LINE_BULLISH_CROSSOVER', 'MACD_SIGNAL_LINE_BEARISH_CROSSOVER', 'RSI_OVERSOLD_REACHED', 'RSI_OVERBOUGHT_REACHED', 'RSI_GROWTH', 'RSI_DECLINE', name='algorithmenum'), nullable=False),
    sa.Column('timeframe', sa.Enum('INTERVAL_1_HOUR', 'INTERVAL_4_HOURS', 'INTERVAL_1_DAY', 'INTERVAL_1_WEEK', 'INTERVAL_1_MONTH', name='timeframeenum'), nullable=False),
    sa.Column('level', sa.Float(), nullable=False),
    sa.Column('moving_average', sa.Enum('SMA20', 'SMA50', 'SMA200', name='movingaverageenum'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_table('exchanges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    schema='trading'
    )
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_table('group_algorithm_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('algorithm_config_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['algorithm_config_id'], ['trading.algorithm_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['trading.groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'algorithm_config_id'),
    schema='trading'
    )
    op.create_table('tickers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('screener', sa.Enum('CRYPTO', 'FOREX', 'CFD', 'STOCKS_US', 'STOCKS_UK', 'STOCKS_JP', 'STOCKS_RU', name='screenerenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['trading.exchanges.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'exchange_id'),
    schema='trading'
    )
    op.create_index(op.f('ix_trading_tickers_key'), 'tickers', ['key'], unique=False, schema='trading')
    op.create_table('signal_calculation_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('signal_expiration_timestamp', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['trading.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticker_id'], ['trading.tickers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index(op.f('ix_trading_signal_calculation_configs_ticker_id'), 'signal_calculation_configs', ['ticker_id'], unique=False, schema='trading')
    op.create_table('signal_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('calculation_config_id', sa.UUID(), nullable=False),
    sa.Column('create_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'SENT', 'FAILED', name='signalstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['calculation_config_id'], ['trading.signal_calculation_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index(op.f('ix_trading_signal_history_calculation_config_id'), 'signal_history', ['calculation_config_id'], unique=False, schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_signal_history_calculation_config_id'), table_name='signal_history', schema='trading')
    op.drop_table('signal_history', schema='trading')
    op.drop_index(op.f('ix_trading_signal_calculation_configs_ticker_id'), table_name='signal_calculation_configs', schema='trading')
    op.drop_table('signal_calculation_configs', schema='trading')
    op.drop_index(op.f('ix_trading_tickers_key'), table_name='tickers', schema='trading')
    op.drop_table('tickers', schema='trading')
    op.drop_table('group_algorithm_configs', schema='trading')
    op.drop_table('groups', schema='trading')
    op.drop_table('exchanges', schema='trading')
    op.drop_table('algorithm_configs', schema='trading')
    # ### end Alembic commands ###
