ZERO_STUB = 0

NEGATIVE_SHARE = -1.0
ZERO_SHARE = 0.0
HALF_SHARE = 0.5
UNIT_SHARE = 1.0
DOUBLE_SHARE = 2.0

NEGATIVE_PERCENT = -1
ZERO = ZERO_PERCENT = 0
TWENTY_FIVE = TWENTY_FIVE_PERCENT = 25
FIFTY = FIFTY_PERCENT = 50
SEVENTY_FIVE = SEVENTY_FIVE_PERCENT = 75
ONE_HUNDRED = ONE_HUNDRED_PERCENT = 100
TWO_HUNDRED_PERCENT = 200
