from datetime import datetime

import uuid

from sqlalchemy import UUID, DateTime, Enum, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column

from src.core.domain.constants.signal_status import SignalStatusEnum
from src.infrastructure.database.models.signal_calculation_config import SignalCalculationConfigModel
from src.infrastructure.database.models.base import Base


class HistoricalSignalModel(Base):
    """
    ORM model for the signal_history table.

    Records each trading signal generated by the evaluator,
    including its creation timestamp and delivery status.
    """

    __tablename__ = "signal_history"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
    )
    calculation_config_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            SignalCalculationConfigModel.id,
            ondelete="CASCADE",
        ),
        nullable=False,
        index=True,
    )
    create_dt: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
    )
    status: Mapped[SignalStatusEnum] = mapped_column(
        Enum(SignalStatusEnum),
        nullable=False,
    )
